---
quditto_version: 2.0
config:
  application_interface: etsi-gs-qkd-014
  qkd_protocol: bb84
  controller: A
  ip_controller: 10.4.48.59
  netsquid_user: user
  netsquid_pwd: pwd


sites:
  - Sevilla
  - Malaga
  - Cadiz

nodes:
  - node_name: A
    node_site: Sevilla
    node_ip: 10.4.48.59
    neighbour_nodes:

      - name: B
        link_length: 154
        protocol: bb84
        eavesdropper: False

      - name: C
        link_legth: 100
        protocol: bb84
        eavesdropper: True
        eavesdropper_parameters:
          eavesdropper_distance: 45
          percentage_intercepted_qubits: 10

  - node_name: B
    node_site: Malaga
    node_ip: 10.4.48.129
    neighbour_nodes:

      - name: A
        link_length: 154
        protocol: bb84
        eavesdropper: False

  - node_name: C
    node_site: Cadiz
    node_ip: 10.4.48.188
    neighbour_nodes:

    - name: A
      link_length: 100
      protocol: bb84
      eavesdropper: True
      eavesdropper_parameters:
        eavesdropper_distance: 55
        percentage_intercepted_qubits: 10



